[build-system]
requires = ["setuptools>=61.0", "wheel", "packaging"]
build-backend = "setuptools.build_meta"

[project]
name = "pyupgradecheck"
version = "0.1.0"
description = "Simple checker for package Python version compatibility"
readme = "README.md"
requires-python = ">=3.8"
authors = [{name = "Tammy DiPrima", email = "tdiprima@yahoo.com"}]
license = {text = "MIT"}
dependencies = [
  "packaging"
]
[project.scripts]
pyupgradecheck = "pyupgradecheck.cli:main"
